obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.67, 0.2225],[0.67, -0.2225],[-0.37, -0.2225],[-0.37, 0.2225]]
robot_radius: 0.5
inflation_radius: 0.3
#inflation_radius: 0.3
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
