global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 1.0
   publish_frequency: 0
   static_map: true
   width: 100
   height: 100
   rolling_window: true
   resolution: 0.03
   transform_tolerance: 1.0
   map_type: costmap
