local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 4
   height: 4
   resolution: 0.1 # 0.05
   transform_tolerance: 1.0
   map_type: costmap
