analyzers:
  motors:
    type:                       diagnostic_aggregator/AnalyzerGroup
    path:                       Motors
    analyzers:
      right_wheel:
        type:                   diagnostic_aggregator/GenericAnalyzer
        path:                   Right Wheel
        timeout:                5.0
        find_and_remove_prefix: rightwheel_driver
        num_items:              2
      left_wheel:
        type:                   diagnostic_aggregator/GenericAnalyzer
        path:                   Lidar
        timeout:                5.0
        find_and_remove_prefix: leftwheel_driver
        num_items:              2

  sensors:
    type:                       diagnostic_aggregator/AnalyzerGroup
    path:                       Sensors
    analyzers:
      lidar:
        type:                   diagnostic_aggregator/GenericAnalyzer
        path:                   Lidar
        timeout:                5.0
        find_and_remove_prefix: sweeplidar_driver
        num_items:              2
      imu:
        type:                   diagnostic_aggregator/GenericAnalyzer
        path:                   IMU
        timeout:                5.0
        find_and_remove_prefix: imu_driver
        num_items:              2
  computers:
    type:                       diagnostic_aggregator/GenericAnalyzer
    path:                       Computers
    contains:                   ['CPU']
  tf_monitor:
    type:                       diagnostic_aggregator/GenericAnalyzer
    path:                       TF
    find_and_remove_prefix:     tf_monitor
  power:
    type:                       diagnostic_aggregator/GenericAnalyzer
    path:                       'Power System'
    timeout:                    5.0
    find_and_remove_prefix:     battery_driver
    num_items:                  1
