# Velocity Controllers ---------------------------------------
bl_wheel_joint_velocity_controller:
  type:                                velocity_controllers/JointVelocityController
  joint:                               bl_wheel_joint
br_wheel_joint_velocity_controller:
  type:                                velocity_controllers/JointVelocityController
  joint:                               br_wheel_joint
fl_wheel_joint_velocity_controller:
  type:                                velocity_controllers/JointVelocityController
  joint:                               fl_wheel_joint
fr_wheel_joint_velocity_controller:
  type:                                velocity_controllers/JointVelocityController
  joint:                               fr_wheel_joint

# Position Controllers ---------------------------------------
bl_steer_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               bl_steer_joint
br_steer_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               br_steer_joint
fl_steer_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               fl_steer_joint
fr_steer_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               fr_steer_joint
