#!/usr/bin/env python
import roslib
import rospy

import tf
from nav_msgs.msg import Odometry


def odometry_cb(msg):
    br = tf.TransformBroadcaster()

    x = msg.pose.pose.position.x
    y = msg.pose.pose.position.y
    z = msg.pose.pose.position.z
    position = (x, y, z)

    x = msg.pose.pose.orientation.x
    y = msg.pose.pose.orientation.y
    z = msg.pose.pose.orientation.z
    w = msg.pose.pose.orientation.w

    orientation = (x, y, z, w)

    br.sendTransform(position,
                     orientation,
                     rospy.Time.now(),
                     msg.child_frame_id,
                     "odom")


if __name__ == '__main__':
    rospy.init_node('fake_odom_broadcaster')
    rospy.Subscriber('/base_pose_ground_truth', Odometry, odometry_cb)
    rospy.spin()
