#!/usr/bin/env python
import roslib
import rospy

from sensor_msgs.msg import Joy
from geometry_msgs.msg import Twist


class JoystickTeleop():
    def __init__(self):
        rospy.init_node('joystick_teleop')

        rospy.Subscriber('/joy', Joy, self.joy_cb)
        self._cmd_vel_pub = rospy.Publisher("cmd_vel", Twist, queue_size=10)

        self._last_enable_button = False
        rospy.spin()

    def joy_cb(self, msg):
        x_axis = msg.axes[1]
        y_axis = msg.axes[0]
        z_axis = msg.axes[2]

        rospy.loginfo("x: %f, y: %f, z: %f", x_axis, y_axis, z_axis)
        twist = Twist()
        twist.linear.x = x_axis * 2
        twist.linear.y = y_axis * 2
        twist.angular.z = z_axis * 4

        enable_button = msg.buttons[0] == 1

        if(enable_button):
            self._cmd_vel_pub.publish(twist)
        elif(enable_button != self._last_enable_button):
            self._cmd_vel_pub.publish(Twist())

        self._last_enable_button = enable_button

if __name__ == '__main__':
    JoystickTeleop()
