<?xml version="1.0"?>
<!-- Guidebot differential drive base -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <include filename="diff_drive_base.gazebo.xacro"/>

  <include filename="../wheels/drive_wheel.urdf.xacro"/>
  <include filename="../wheels/caster.urdf.xacro"/>

  <!-- Drive wheel characteristics -->
  <property name="wheel_radius"     value="0.13"/>
  <property name="wheel_width"      value="0.05"/>
  <property name="wheel_separation" value="0.65"/>
  <property name="wheel_torque"     value="6.0"/>
  <property name="wheel_velocity"   value="1.0"/>

  <!-- Caster characteristics -->
  <property name="caster_radius" value="0.07"/>
  <property name="caster_ground_offset" value="0.005"/>

  <!-- Base -->
  <macro name="base">
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0.04" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.2" radius="0.3"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin xyz="0 0 0.04" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.2" radius="0.3"/>
        </geometry>
        <material name="orange"/>
      </collision>

      <!-- TODO: update according to real base properties -->
      <inertial>
        <origin xyz="-0.00000106 0.00000109 0.0000387" rpy="0 0 0"/>
        <mass value="15.0"/>
        <inertia ixx="0.465408937" ixy="0.002160024" ixz="-0.001760255"
                 iyy="0.483193291" iyz="-0.000655952"
                 izz="0.550939703"/>
      </inertial>
    </link>

    <!-- Base footprint -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>


    <!-- Macros -->
    <drive_wheel name="wheel_right" radius="${wheel_radius}" width="${wheel_width}" separation="${wheel_separation}" reflect="1.0" parent="base_link"/>
    <drive_wheel name="wheel_left" radius="${wheel_radius}" width="${wheel_width}" separation="${wheel_separation}" reflect="-1.0" parent="base_link"/>

    <caster name="front_caster" radius="${caster_radius}" x_offset="0.2" z_offset="${caster_ground_offset - (wheel_radius - caster_radius)}" parent="base_link"/>
    <caster name="rear_caster" radius="${caster_radius}" x_offset="-0.2" z_offset="${caster_ground_offset - (wheel_radius - caster_radius)}" parent="base_link"/>


    <!-- Gazebo extentions -->
    <diff_drive_base_gazebo/>
  </macro>

</robot>
